// <auto-generated />
using System;
using Inventory.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.Api.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Inventory.Api.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Portable computers and notebooks",
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Desktop computers and workstations",
                            Name = "Desktops"
                        },
                        new
                        {
                            Id = 3,
                            Description = "External displays and monitors",
                            Name = "Monitors"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Mechanical and membrane keyboards",
                            Name = "Keyboards"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Wired and wireless pointing devices",
                            Name = "Mice"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Routers, switches, cables",
                            Name = "Networking"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Hard drives, SSDs, USB drives",
                            Name = "Storage"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Laser and inkjet printers",
                            Name = "Printers"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Cables, adapters, stands",
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Headphones, speakers, microphones",
                            Name = "Audio"
                        });
                });

            modelBuilder.Entity("Inventory.Api.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "14-inch ultrabook, 16GB RAM, 512GB SSD",
                            Name = "Acme Pro 14 Laptop",
                            QuantityInStock = 25,
                            ReorderLevel = 5,
                            Sku = "LAP-001",
                            SupplierId = 1,
                            UnitPrice = 1299.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "15-inch gaming laptop, RTX GPU",
                            Name = "Acme Gamer 15 Laptop",
                            QuantityInStock = 12,
                            ReorderLevel = 4,
                            Sku = "LAP-002",
                            SupplierId = 2,
                            UnitPrice = 1899.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compact desktop for office use",
                            Name = "WorkStation Mini Tower",
                            QuantityInStock = 18,
                            ReorderLevel = 5,
                            Sku = "DSK-001",
                            SupplierId = 1,
                            UnitPrice = 899.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "27-inch 4K UHD IPS display",
                            Name = "27\" 4K IPS Monitor",
                            QuantityInStock = 30,
                            ReorderLevel = 8,
                            Sku = "MON-001",
                            SupplierId = 3,
                            UnitPrice = 549.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "24-inch 1080p office display",
                            Name = "24\" FHD Business Monitor",
                            QuantityInStock = 40,
                            ReorderLevel = 10,
                            Sku = "MON-002",
                            SupplierId = 3,
                            UnitPrice = 199.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mechanical keyboard with RGB backlight",
                            Name = "Mechanical RGB Keyboard",
                            QuantityInStock = 55,
                            ReorderLevel = 12,
                            Sku = "KBD-001",
                            SupplierId = 5,
                            UnitPrice = 129.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bluetooth low-profile keyboard",
                            Name = "Wireless Slim Keyboard",
                            QuantityInStock = 3,
                            ReorderLevel = 10,
                            Sku = "KBD-002",
                            SupplierId = 10,
                            UnitPrice = 79.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomic wireless mouse",
                            Name = "Wireless Ergonomic Mouse",
                            QuantityInStock = 80,
                            ReorderLevel = 15,
                            Sku = "MSE-001",
                            SupplierId = 10,
                            UnitPrice = 39.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dual-band Wi-Fi 6 router, 4 LAN ports",
                            Name = "Wi-Fi 6 Router",
                            QuantityInStock = 22,
                            ReorderLevel = 5,
                            Sku = "NET-001",
                            SupplierId = 4,
                            UnitPrice = 179.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Unmanaged 24-port gigabit switch",
                            Name = "24-Port Gigabit Switch",
                            QuantityInStock = 8,
                            ReorderLevel = 3,
                            Sku = "NET-002",
                            SupplierId = 4,
                            UnitPrice = 219.00m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "M.2 NVMe SSD 1TB",
                            Name = "1TB NVMe SSD",
                            QuantityInStock = 45,
                            ReorderLevel = 10,
                            Sku = "STO-001",
                            SupplierId = 5,
                            UnitPrice = 119.00m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "USB 3.0 portable hard drive",
                            Name = "2TB External HDD",
                            QuantityInStock = 35,
                            ReorderLevel = 8,
                            Sku = "STO-002",
                            SupplierId = 7,
                            UnitPrice = 89.00m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wi-Fi color laser printer",
                            Name = "Color Laser Printer",
                            QuantityInStock = 6,
                            ReorderLevel = 2,
                            Sku = "PRN-001",
                            SupplierId = 9,
                            UnitPrice = 329.00m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "7-port USB-C hub with HDMI",
                            Name = "USB-C Hub 7-in-1",
                            QuantityInStock = 120,
                            ReorderLevel = 20,
                            Sku = "ACC-001",
                            SupplierId = 8,
                            UnitPrice = 49.00m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Over-ear ANC headphones",
                            Name = "Noise-Cancelling Headset",
                            QuantityInStock = 15,
                            ReorderLevel = 5,
                            Sku = "AUD-001",
                            SupplierId = 6,
                            UnitPrice = 249.00m
                        });
                });

            modelBuilder.Entity("Inventory.Api.Domain.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovementType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("StockTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovementType = 0,
                            Note = "Initial shipment",
                            OccurredAt = new DateTime(2026, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            PerformedBy = "seed",
                            ProductId = 1,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 2,
                            MovementType = 1,
                            Note = "Order #1001",
                            OccurredAt = new DateTime(2026, 2, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            PerformedBy = "seed",
                            ProductId = 1,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 3,
                            MovementType = 0,
                            Note = "Initial shipment",
                            OccurredAt = new DateTime(2026, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            PerformedBy = "seed",
                            ProductId = 2,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 4,
                            MovementType = 0,
                            Note = "Initial shipment",
                            OccurredAt = new DateTime(2026, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            PerformedBy = "seed",
                            ProductId = 3,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 5,
                            MovementType = 0,
                            Note = "Initial shipment",
                            OccurredAt = new DateTime(2026, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            PerformedBy = "seed",
                            ProductId = 4,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 6,
                            MovementType = 1,
                            Note = "Bulk order",
                            OccurredAt = new DateTime(2026, 2, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            PerformedBy = "seed",
                            ProductId = 5,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 7,
                            MovementType = 0,
                            Note = "Restock",
                            OccurredAt = new DateTime(2026, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            PerformedBy = "seed",
                            ProductId = 6,
                            Quantity = 60
                        },
                        new
                        {
                            Id = 8,
                            MovementType = 1,
                            Note = "Online order",
                            OccurredAt = new DateTime(2026, 2, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            PerformedBy = "seed",
                            ProductId = 7,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 9,
                            MovementType = 2,
                            Note = "Damaged stock write-off",
                            OccurredAt = new DateTime(2026, 2, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            PerformedBy = "seed",
                            ProductId = 8,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 10,
                            MovementType = 0,
                            Note = "Initial shipment",
                            OccurredAt = new DateTime(2026, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            PerformedBy = "seed",
                            ProductId = 9,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 11,
                            MovementType = 0,
                            Note = "Restock",
                            OccurredAt = new DateTime(2026, 2, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            PerformedBy = "seed",
                            ProductId = 11,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 12,
                            MovementType = 0,
                            Note = "Bulk restock",
                            OccurredAt = new DateTime(2026, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            PerformedBy = "seed",
                            ProductId = 14,
                            Quantity = 120
                        });
                });

            modelBuilder.Entity("Inventory.Api.Domain.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "120 King St W, Toronto, ON",
                            ContactName = "Alice Nguyen",
                            Email = "sales@techworld.example",
                            Name = "TechWorld Distributors",
                            Phone = "+1-416-555-0101"
                        },
                        new
                        {
                            Id = 2,
                            Address = "88 Queen St E, Toronto, ON",
                            ContactName = "Raj Patel",
                            Email = "orders@bytemart.example",
                            Name = "ByteMart Wholesale",
                            Phone = "+1-416-555-0102"
                        },
                        new
                        {
                            Id = 3,
                            Address = "45 Main St, Mississauga, ON",
                            ContactName = "Emily Chen",
                            Email = "hello@pixelpro.example",
                            Name = "PixelPro Supply",
                            Phone = "+1-905-555-0103"
                        },
                        new
                        {
                            Id = 4,
                            Address = "210 Industrial Rd, Brampton, ON",
                            ContactName = "David Kim",
                            Email = "ops@netgearlog.example",
                            Name = "NetGear Logistics",
                            Phone = "+1-905-555-0104"
                        },
                        new
                        {
                            Id = 5,
                            Address = "300 Bay St, Toronto, ON",
                            ContactName = "Sara Lopez",
                            Email = "info@corecircuit.example",
                            Name = "CoreCircuit Parts",
                            Phone = "+1-647-555-0105"
                        },
                        new
                        {
                            Id = 6,
                            Address = "14 Bloor St W, Toronto, ON",
                            ContactName = "Michael Brown",
                            Email = "contact@synapse.example",
                            Name = "Synapse Electronics",
                            Phone = "+1-647-555-0106"
                        },
                        new
                        {
                            Id = 7,
                            Address = "500 University Ave, Toronto, ON",
                            ContactName = "Olivia Wilson",
                            Email = "sales@northstarit.example",
                            Name = "NorthStar IT Supply",
                            Phone = "+1-416-555-0107"
                        },
                        new
                        {
                            Id = 8,
                            Address = "22 Dundas Sq, Toronto, ON",
                            ContactName = "Liam O'Connor",
                            Email = "support@quantumg.example",
                            Name = "Quantum Gadgets",
                            Phone = "+1-416-555-0108"
                        },
                        new
                        {
                            Id = 9,
                            Address = "77 Yonge St, Richmond Hill, ON",
                            ContactName = "Aisha Khan",
                            Email = "orders@orbitoffice.example",
                            Name = "Orbit Office Supply",
                            Phone = "+1-905-555-0109"
                        },
                        new
                        {
                            Id = 10,
                            Address = "99 Dufferin St, Vaughan, ON",
                            ContactName = "Noah Smith",
                            Email = "hello@peakperi.example",
                            Name = "Peak Peripherals",
                            Phone = "+1-905-555-0110"
                        });
                });

            modelBuilder.Entity("Inventory.Api.Domain.Product", b =>
                {
                    b.HasOne("Inventory.Api.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inventory.Api.Domain.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Inventory.Api.Domain.StockTransaction", b =>
                {
                    b.HasOne("Inventory.Api.Domain.Product", "Product")
                        .WithMany("StockTransactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Inventory.Api.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Inventory.Api.Domain.Product", b =>
                {
                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("Inventory.Api.Domain.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
